print("Olá vamos calcular seu IMC 'indice de massa corporal.'")
nome = input("Primeiro digite seu nome.")
print("Obrigado", nome)
peso = float(input('Agora digite seu peso.'))
print("Obrigado" , nome , "seu peso é", peso)
altura = float(input('Agora digite sua altura.'))
print("Então ", nome , " seu peso é ", peso , "e sua altura é", altura)
imc = peso / (altura*altura)
print("O seu indice de massa corporal ou simplesmente 'IMC' é", imc)